--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.150.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 07.07.2026 23:51:33
-- Server version: 8.0.42
--

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Set SQL mode
--
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';


DROP DATABASE IF EXISTS practic;


CREATE DATABASE practic;

--
-- Set default database
--
USE practic;

--
-- Drop table `client_language`
--
DROP TABLE IF EXISTS client_language;

--
-- Drop table `clients`
--
DROP TABLE IF EXISTS clients;

--
-- Drop table `worker_language`
--
DROP TABLE IF EXISTS worker_language;

--
-- Drop table `languages`
--
DROP TABLE IF EXISTS languages;

--
-- Drop table `lenguage_levele`
--
DROP TABLE IF EXISTS lenguage_levele;

--
-- Drop table `workers`
--
DROP TABLE IF EXISTS workers;

--
-- Set default database
--
USE practic;

--
-- Create table `workers`
--
CREATE TABLE workers (
  id bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Код сотрудника',
  name varchar(100) NOT NULL COMMENT 'Имя работника',
  surname varchar(100) NOT NULL COMMENT 'Фамилия работника',
  patronymic varchar(100) DEFAULT NULL COMMENT 'Отчество работника',
  telephone varchar(50) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Работники',
ROW_FORMAT = DYNAMIC;

--
-- Create table `lenguage_levele`
--
CREATE TABLE lenguage_levele (
  id tinyint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Код уровня освоения языка',
  name_level varchar(5) DEFAULT NULL COMMENT 'Название уровня освоения языка',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Уровни освоения языков',
ROW_FORMAT = DYNAMIC;

--
-- Create table `languages`
--
CREATE TABLE languages (
  id int UNSIGNED NOT NULL COMMENT 'Код языка',
  name varchar(50) NOT NULL COMMENT 'Название языка',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Языки',
ROW_FORMAT = DYNAMIC;

--
-- Create table `worker_language`
--
CREATE TABLE worker_language (
  id_worker bigint UNSIGNED NOT NULL,
  id_language int UNSIGNED NOT NULL,
  id_level tinyint UNSIGNED DEFAULT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Языки которые знают работники',
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE worker_language
ADD CONSTRAINT FK_Worker_Language_id_language FOREIGN KEY (id_language)
REFERENCES languages (id);

--
-- Create foreign key
--
ALTER TABLE worker_language
ADD CONSTRAINT FK_worker_language_id_level FOREIGN KEY (id_level)
REFERENCES lenguage_levele (id);

--
-- Create foreign key
--
ALTER TABLE worker_language
ADD CONSTRAINT FK_Worker_Language_id_worker FOREIGN KEY (id_worker)
REFERENCES workers (id);

--
-- Create table `clients`
--
CREATE TABLE clients (
  id bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Код клиента',
  name varchar(100) NOT NULL COMMENT 'Имя пользователя',
  surname varchar(100) NOT NULL COMMENT 'Фамилия клиента',
  patronymic varchar(100) DEFAULT NULL COMMENT 'Отчество клиента',
  telephone varchar(50) NOT NULL COMMENT 'Телефон клиента',
  street varchar(100) NOT NULL COMMENT 'Улица клиента',
  house varchar(100) NOT NULL COMMENT 'Дом клиента',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Клиенты',
ROW_FORMAT = DYNAMIC;

--
-- Create table `client_language`
--
CREATE TABLE client_language (
  id_client bigint UNSIGNED NOT NULL,
  id_language int UNSIGNED NOT NULL,
  id_level tinyint UNSIGNED DEFAULT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Языки которые знают клиенты',
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE client_language
ADD CONSTRAINT FK_client_language_id_client FOREIGN KEY (id_client)
REFERENCES clients (id);

--
-- Create foreign key
--
ALTER TABLE client_language
ADD CONSTRAINT FK_client_language_id_language FOREIGN KEY (id_language)
REFERENCES languages (id);

--
-- Create foreign key
--
ALTER TABLE client_language
ADD CONSTRAINT FK_client_language_id_level FOREIGN KEY (id_level)
REFERENCES lenguage_levele (id);

-- 
-- Dumping data for table workers
--
INSERT INTO workers VALUES
(1, 'Александр', 'Иванов', 'Петрович', '+79991110001'),
(2, 'Максим', 'Смирнов', 'Алексеевич', '+79991110002'),
(3, 'Елена', 'Кузнецова', 'Викторовна', '+79991110003'),
(4, 'Ольга', 'Попова', NULL, '+79991110004'),
(5, 'Дмитрий', 'Соколов', 'Сергеевич', '+79991110005'),
(6, 'Наталья', 'Лебедева', 'Игоревна', '+79991110006'),
(7, 'Андрей', 'Козлов', 'Николаевич', '+79991110007'),
(8, 'Татьяна', 'Новикова', 'Владимировна', '+79991110008'),
(9, 'Сергей', 'Морозов', NULL, '+79991110009'),
(10, 'Марина', 'Васильева', 'Андреевна', '+79991110010');

-- 
-- Dumping data for table lenguage_levele
--
INSERT INTO lenguage_levele VALUES
(1, 'A1'),
(2, 'A2'),
(3, 'B1'),
(4, 'B2'),
(5, 'C1'),
(6, 'C2'),
(7, 'F');

-- 
-- Dumping data for table languages
--
INSERT INTO languages VALUES
(1, 'Русский'),
(2, 'Английский'),
(3, 'Немецкий'),
(4, 'Французский'),
(5, 'Испанский'),
(6, 'Итальянский'),
(7, 'Китайский'),
(8, 'Японский'),
(9, 'Корейский'),
(10, 'Арабский');

-- 
-- Dumping data for table clients
--
INSERT INTO clients VALUES
(1, 'Иван', 'Иванов', 'Иванович', '+79990000001', 'ул. Ленина', '10'),
(2, 'Петр', 'Петров', 'Петрович', '+79990000002', 'ул. Гагарина', '15'),
(3, 'Алексей', 'Сидоров', 'Викторович', '+79990000003', 'ул. Советская', '22'),
(4, 'Мария', 'Кузнецова', 'Андреевна', '+79990000004', 'ул. Молодежная', '8'),
(5, 'Анна', 'Смирнова', NULL, '+79990000005', 'ул. Центральная', '45'),
(6, 'Дмитрий', 'Волков', 'Сергеевич', '+79990000006', 'ул. Школьная', '3'),
(7, 'Сергей', 'Федоров', 'Алексеевич', '+79990000008', 'ул. Победы', '29'),
(8, 'Ольга', 'Николаева', 'Владимировна', '+79990000009', 'ул. Садовая', '12'),
(9, 'Николай', 'Орлов', NULL, '+79990000010', 'ул. Лесная', '7');

-- 
-- Dumping data for table worker_language
--
INSERT INTO worker_language VALUES
(1, 1, 1),
(1, 2, 2),
(2, 1, 3),
(2, 3, 4),
(3, 2, 5),
(4, 4, 6),
(5, 5, 7),
(6, 1, NULL),
(6, 7, NULL),
(8, 9, NULL);

-- 
-- Dumping data for table client_language
--
INSERT INTO client_language VALUES
(1, 1, 1),
(1, 2, 2),
(2, 1, 3),
(2, 3, 4),
(3, 1, 5),
(4, 2, 6),
(5, 5, 7),
(6, 4, NULL),
(7, 2, NULL),
(7, 8, NULL);

--
-- Restore previous SQL mode
--
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;