



partial class MainForm{
    private System.ComponentModel.IContainer components = null;

    protected override void Dispose(bool disposing){
        if (disposing && (components != null)){components.Dispose();}
        base.Dispose(disposing);
    }

    private void InitializeComponent(){
        label1 = new Label();
        save_data = new Button();
        data_input = new TextBox();
        tableLayoutPanel1 = new TableLayoutPanel();
        groupBox1 = new GroupBox();
        tableLayoutPanel2 = new TableLayoutPanel();
        label5 = new Label();
        label6 = new Label();
        S1 = new Label();
        S1S2 = new Label();
        S1E = new Label();
        label10 = new Label();
        S2 = new Label();
        S2S2 = new Label();
        S2S3 = new Label();
        S2_0 = new Label();
        S3 = new Label();
        S3S2 = new Label();
        S3S3 = new Label();
        S3_1 = new Label();
        E = new Label();
        E_0 = new Label();
        E_1 = new Label();
        label7 = new Label();
        label2 = new Label();
        print_data = new Label();
        label3 = new Label();
        selected_char = new Label();
        label4 = new Label();
        number_selected_char = new Label();
        tableLayoutPanel1.SuspendLayout();
        groupBox1.SuspendLayout();
        tableLayoutPanel2.SuspendLayout();
        SuspendLayout();
        label1.AutoSize = true;
        label1.Dock = DockStyle.Top;
        label1.Location = new Point(3, 0);
        label1.Name = "label1";
        label1.Size = new Size(153, 15);
        label1.TabIndex = 0;
        label1.Text = "Введите данные:";
        save_data.AutoSize = true;
        save_data.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        save_data.Dock = DockStyle.Top;
        save_data.Location = new Point(361, 3);
        save_data.Name = "save_data";
        save_data.Size = new Size(120, 25);
        save_data.TabIndex = 1;
        save_data.Text = "Сохранить данные";
        save_data.UseVisualStyleBackColor = true;
        save_data.Click += save_data_Click;
        data_input.Dock = DockStyle.Top;
        data_input.Location = new Point(162, 3);
        data_input.Name = "data_input";
        data_input.Size = new Size(193, 23);
        data_input.TabIndex = 2;
        tableLayoutPanel1.AutoSize = true;
        tableLayoutPanel1.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        tableLayoutPanel1.ColumnCount = 3;
        tableLayoutPanel1.ColumnStyles.Add(new ColumnStyle());
        tableLayoutPanel1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        tableLayoutPanel1.ColumnStyles.Add(new ColumnStyle());
        tableLayoutPanel1.Controls.Add(groupBox1, 1, 4);
        tableLayoutPanel1.Controls.Add(label1, 0, 0);
        tableLayoutPanel1.Controls.Add(save_data, 2, 0);
        tableLayoutPanel1.Controls.Add(data_input, 1, 0);
        tableLayoutPanel1.Controls.Add(label2, 0, 1);
        tableLayoutPanel1.Controls.Add(print_data, 1, 1);
        tableLayoutPanel1.Controls.Add(label3, 0, 2);
        tableLayoutPanel1.Controls.Add(selected_char, 1, 2);
        tableLayoutPanel1.Controls.Add(label4, 0, 3);
        tableLayoutPanel1.Controls.Add(number_selected_char, 1, 3);
        tableLayoutPanel1.Dock = DockStyle.Fill;
        tableLayoutPanel1.Location = new Point(0, 0);
        tableLayoutPanel1.Name = "tableLayoutPanel1";
        tableLayoutPanel1.RowCount = 5;
        tableLayoutPanel1.RowStyles.Add(new RowStyle());
        tableLayoutPanel1.RowStyles.Add(new RowStyle());
        tableLayoutPanel1.RowStyles.Add(new RowStyle());
        tableLayoutPanel1.RowStyles.Add(new RowStyle());
        tableLayoutPanel1.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        tableLayoutPanel1.Size = new Size(484, 211);
        tableLayoutPanel1.TabIndex = 3;
        groupBox1.AutoSize = true;
        groupBox1.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        groupBox1.Controls.Add(tableLayoutPanel2);
        groupBox1.Dock = DockStyle.Fill;
        groupBox1.Location = new Point(162, 79);
        groupBox1.Name = "groupBox1";
        groupBox1.Size = new Size(193, 129);
        groupBox1.TabIndex = 4;
        groupBox1.TabStop = false;
        groupBox1.Text = "Таблица обработки";
        tableLayoutPanel2.AutoSize = true;
        tableLayoutPanel2.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        tableLayoutPanel2.ColumnCount = 4;
        tableLayoutPanel2.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
        tableLayoutPanel2.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
        tableLayoutPanel2.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
        tableLayoutPanel2.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
        tableLayoutPanel2.Controls.Add(label5, 1, 0);
        tableLayoutPanel2.Controls.Add(label6, 2, 0);
        tableLayoutPanel2.Controls.Add(S1, 0, 1);
        tableLayoutPanel2.Controls.Add(S1S2, 1, 1);
        tableLayoutPanel2.Controls.Add(S1E, 2, 1);
        tableLayoutPanel2.Controls.Add(label10, 3, 1);
        tableLayoutPanel2.Controls.Add(S2, 0, 2);
        tableLayoutPanel2.Controls.Add(S2S2, 1, 2);
        tableLayoutPanel2.Controls.Add(S2S3, 2, 2);
        tableLayoutPanel2.Controls.Add(S2_0, 3, 2);
        tableLayoutPanel2.Controls.Add(S3, 0, 3);
        tableLayoutPanel2.Controls.Add(S3S2, 1, 3);
        tableLayoutPanel2.Controls.Add(S3S3, 2, 3);
        tableLayoutPanel2.Controls.Add(S3_1, 3, 3);
        tableLayoutPanel2.Controls.Add(E, 0, 4);
        tableLayoutPanel2.Controls.Add(E_0, 1, 4);
        tableLayoutPanel2.Controls.Add(E_1, 2, 4);
        tableLayoutPanel2.Controls.Add(label7, 3, 4);
        tableLayoutPanel2.Dock = DockStyle.Fill;
        tableLayoutPanel2.Location = new Point(3, 19);
        tableLayoutPanel2.Name = "tableLayoutPanel2";
        tableLayoutPanel2.RowCount = 5;
        tableLayoutPanel2.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
        tableLayoutPanel2.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
        tableLayoutPanel2.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
        tableLayoutPanel2.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
        tableLayoutPanel2.RowStyles.Add(new RowStyle(SizeType.Percent, 20F));
        tableLayoutPanel2.Size = new Size(187, 107);
        tableLayoutPanel2.TabIndex = 5;
        label5.AutoSize = true;
        label5.Dock = DockStyle.Fill;
        label5.Location = new Point(49, 0);
        label5.Name = "label5";
        label5.Size = new Size(40, 21);
        label5.TabIndex = 0;
        label5.Text = "0";
        label5.TextAlign = ContentAlignment.MiddleCenter;
        label6.AutoSize = true;
        label6.Dock = DockStyle.Fill;
        label6.Location = new Point(95, 0);
        label6.Name = "label6";
        label6.Size = new Size(40, 21);
        label6.TabIndex = 1;
        label6.Text = "1";
        label6.TextAlign = ContentAlignment.MiddleCenter;
        S1.AutoSize = true;
        S1.Dock = DockStyle.Fill;
        S1.Location = new Point(3, 21);
        S1.Name = "S1";
        S1.Size = new Size(40, 21);
        S1.TabIndex = 2;
        S1.Text = "S1";
        S1.TextAlign = ContentAlignment.MiddleCenter;
        S1S2.AutoSize = true;
        S1S2.Dock = DockStyle.Fill;
        S1S2.Location = new Point(49, 21);
        S1S2.Name = "S1S2";
        S1S2.Size = new Size(40, 21);
        S1S2.TabIndex = 3;
        S1S2.Text = "S2";
        S1S2.TextAlign = ContentAlignment.MiddleCenter; 
        S1E.AutoSize = true;
        S1E.Dock = DockStyle.Fill;
        S1E.Location = new Point(95, 21);
        S1E.Name = "S1E";
        S1E.Size = new Size(40, 21);
        S1E.TabIndex = 4;
        S1E.Text = "E";
        S1E.TextAlign = ContentAlignment.MiddleCenter;
        label10.AutoSize = true;
        label10.Dock = DockStyle.Fill;
        label10.Location = new Point(141, 21);
        label10.Name = "label10";
        label10.Size = new Size(43, 21);
        label10.TabIndex = 5;
        label10.Text = "0";
        label10.TextAlign = ContentAlignment.MiddleCenter;
        S2.AutoSize = true;
        S2.Dock = DockStyle.Fill;
        S2.Location = new Point(3, 42);
        S2.Name = "S2";
        S2.Size = new Size(40, 21);
        S2.TabIndex = 6;
        S2.Text = "S2";
        S2.TextAlign = ContentAlignment.MiddleCenter;
        S2S2.AutoSize = true;
        S2S2.Dock = DockStyle.Fill;
        S2S2.Location = new Point(49, 42);
        S2S2.Name = "S2S2";
        S2S2.Size = new Size(40, 21);
        S2S2.TabIndex = 7;
        S2S2.Text = "S2";
        S2S2.TextAlign = ContentAlignment.MiddleCenter;
        S2S3.AutoSize = true;
        S2S3.Dock = DockStyle.Fill;
        S2S3.Location = new Point(95, 42);
        S2S3.Name = "S2S3";
        S2S3.Size = new Size(40, 21);
        S2S3.TabIndex = 8;
        S2S3.Text = "S3";
        S2S3.TextAlign = ContentAlignment.MiddleCenter;
        S2_0.AutoSize = true;
        S2_0.Dock = DockStyle.Fill;
        S2_0.Location = new Point(141, 42);
        S2_0.Name = "S2_0";
        S2_0.Size = new Size(43, 21);
        S2_0.TabIndex = 9;
        S2_0.Text = "0";
        S2_0.TextAlign = ContentAlignment.MiddleCenter;
        S3.AutoSize = true;
        S3.Dock = DockStyle.Fill;
        S3.Location = new Point(3, 63);
        S3.Name = "S3";
        S3.Size = new Size(40, 21);
        S3.TabIndex = 10;
        S3.Text = "S3";
        S3.TextAlign = ContentAlignment.MiddleCenter;
        S3S2.AutoSize = true;
        S3S2.Dock = DockStyle.Fill;
        S3S2.Location = new Point(49, 63);
        S3S2.Name = "S3S2";
        S3S2.Size = new Size(40, 21);
        S3S2.TabIndex = 11;
        S3S2.Text = "S2";
        S3S2.TextAlign = ContentAlignment.MiddleCenter;
        S3S3.AutoSize = true;
        S3S3.Dock = DockStyle.Fill;
        S3S3.Location = new Point(95, 63);
        S3S3.Name = "S3S3";
        S3S3.Size = new Size(40, 21);
        S3S3.TabIndex = 12;
        S3S3.Text = "S3";
        S3S3.TextAlign = ContentAlignment.MiddleCenter;
        S3_1.AutoSize = true;
        S3_1.Dock = DockStyle.Fill;
        S3_1.Location = new Point(141, 63);
        S3_1.Name = "S3_1";
        S3_1.Size = new Size(43, 21);
        S3_1.TabIndex = 13;
        S3_1.Text = "1";
        S3_1.TextAlign = ContentAlignment.MiddleCenter;
        E.AutoSize = true;
        E.Dock = DockStyle.Fill;
        E.Location = new Point(3, 84);
        E.Name = "E";
        E.Size = new Size(40, 23);
        E.TabIndex = 14;
        E.Text = "E";
        E.TextAlign = ContentAlignment.MiddleCenter;
        E_0.AutoSize = true;
        E_0.Dock = DockStyle.Fill;
        E_0.Location = new Point(49, 84);
        E_0.Name = "E_0";
        E_0.Size = new Size(40, 23);
        E_0.TabIndex = 15;
        E_0.Text = "E";
        E_0.TextAlign = ContentAlignment.MiddleCenter;
        E_1.AutoSize = true;
        E_1.Dock = DockStyle.Fill;
        E_1.Location = new Point(95, 84);
        E_1.Name = "E_1";
        E_1.Size = new Size(40, 23);
        E_1.TabIndex = 16;
        E_1.Text = "E";
        E_1.TextAlign = ContentAlignment.MiddleCenter;
        label7.AutoSize = true;
        label7.Dock = DockStyle.Fill;
        label7.Location = new Point(141, 84);
        label7.Name = "label7";
        label7.Size = new Size(43, 23);
        label7.TabIndex = 17;
        label7.Text = "0";
        label7.TextAlign = ContentAlignment.MiddleCenter;
        label2.AutoSize = true;
        label2.Dock = DockStyle.Top;
        label2.Location = new Point(3, 31);
        label2.Name = "label2";
        label2.Size = new Size(153, 15);
        label2.TabIndex = 3;
        label2.Text = "Данные которые вы ввели";
        print_data.AutoSize = true;
        print_data.Dock = DockStyle.Top;
        print_data.Location = new Point(162, 31);
        print_data.Name = "print_data";
        print_data.Size = new Size(193, 15);
        print_data.TabIndex = 4;
        print_data.Text = "Вы не ввели данные";
        label3.AutoSize = true;
        label3.Dock = DockStyle.Top;
        label3.Location = new Point(3, 46);
        label3.Name = "label3";
        label3.Size = new Size(153, 15);
        label3.TabIndex = 5;
        label3.Text = "Обрабатываемый символ";
        selected_char.AutoSize = true;
        selected_char.Dock = DockStyle.Top;
        selected_char.Location = new Point(162, 46);
        selected_char.Name = "selected_char";
        selected_char.Size = new Size(193, 15);
        selected_char.TabIndex = 6;
        selected_char.Text = "Символ не указан";
        label4.AutoSize = true;
        label4.Dock = DockStyle.Top;
        label4.Location = new Point(3, 61);
        label4.Name = "label4";
        label4.Size = new Size(153, 15);
        label4.TabIndex = 7;
        label4.Text = "Номер символа";
        number_selected_char.AutoSize = true;
        number_selected_char.Dock = DockStyle.Top;
        number_selected_char.Location = new Point(162, 61);
        number_selected_char.Name = "number_selected_char";
        number_selected_char.Size = new Size(193, 15);
        number_selected_char.TabIndex = 8;
        number_selected_char.Text = "Номер сивола не указан";
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        ClientSize = new Size(484, 211);
        Controls.Add(tableLayoutPanel1);
        MinimumSize = new Size(500, 250);
        Name = "MainForm";
        Text = "Буханов Д.Е. Группа 3105 об. Вариант 4";
        tableLayoutPanel1.ResumeLayout(false);
        tableLayoutPanel1.PerformLayout();
        groupBox1.ResumeLayout(false);
        groupBox1.PerformLayout();
        tableLayoutPanel2.ResumeLayout(false);
        tableLayoutPanel2.PerformLayout();
        ResumeLayout(false);
        PerformLayout();
    }
    private Label label1;
    private Button save_data;
    private TextBox data_input;
    private TableLayoutPanel tableLayoutPanel1;
    private Label label2;
    private Label print_data;
    private Label label3;
    private Label selected_char;
    private Label label4;
    private Label number_selected_char;
    private GroupBox groupBox1;
    private TableLayoutPanel tableLayoutPanel2;
    private Label label5;
    private Label label6;
    private Label S1;
    private Label S1S2;
    private Label S1E;
    private Label label10;
    private Label S2;
    private Label S2S2;
    private Label S2S3;
    private Label S2_0;
    private Label S3;
    private Label S3S2;
    private Label S3S3;
    private Label S3_1;
    private Label E;
    private Label E_0;
    private Label E_1;
    private Label label7;
}
