--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.150.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 18.12.2025 21:50:20
-- Server version: 8.0.42
--

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Set SQL mode
--
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';


DROP database IF EXISTS `position`;

Create database `position`;


--
-- Set default database
--
USE `position`;

--
-- Drop table `order`
--
DROP TABLE IF EXISTS `order`;

--
-- Drop table `vision`
--
DROP TABLE IF EXISTS vision;

--
-- Drop table `possessions`
--
DROP TABLE IF EXISTS possessions;

--
-- Drop table `salesmans`
--
DROP TABLE IF EXISTS salesmans;

--
-- Drop table `customer`
--
DROP TABLE IF EXISTS customer;

--
-- Drop table `type_position`
--
DROP TABLE IF EXISTS type_position;

--
-- Drop table `rieltor`
--
DROP TABLE IF EXISTS rieltor;

--
-- Drop table `department`
--
DROP TABLE IF EXISTS department;

--
-- Set default database
--
USE `position`;

--
-- Create table `department`
--
CREATE TABLE department (
  id bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Код релторской компании',
  name varchar(255) DEFAULT NULL COMMENT 'Название филиала',
  `describe` text DEFAULT NULL COMMENT 'Описание филиала',
  city varchar(255) DEFAULT NULL COMMENT 'Город филиала',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1638,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Релторские филиалы',
ROW_FORMAT = DYNAMIC;

--
-- Create table `rieltor`
--
CREATE TABLE rieltor (
  id bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Код релтора',
  name varchar(50) DEFAULT NULL COMMENT 'ФИО',
  id_company bigint UNSIGNED NOT NULL COMMENT 'Код компании',
  salary int DEFAULT NULL COMMENT 'Зарплата',
  sex varchar(255) DEFAULT NULL COMMENT 'Пол',
  birthday date DEFAULT NULL COMMENT 'Дата рождения',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Риэлтор',
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE rieltor
ADD CONSTRAINT FK_rieltor_id_company FOREIGN KEY (id_company)
REFERENCES department (id);

--
-- Create table `type_position`
--
CREATE TABLE type_position (
  id bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  name varchar(100) DEFAULT NULL COMMENT 'Название типа',
  `describe` varchar(255) DEFAULT NULL COMMENT 'Описание типа',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Тип имущества',
ROW_FORMAT = DYNAMIC;

--
-- Create table `customer`
--
CREATE TABLE customer (
  id bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Код клиента',
  name varchar(50) DEFAULT NULL COMMENT 'ФИО клиента',
  phone varchar(255) DEFAULT NULL COMMENT 'Номер клиента',
  id_type bigint UNSIGNED NOT NULL COMMENT 'Желаемый тип недвижимости',
  sex varchar(255) DEFAULT NULL COMMENT 'Пол',
  city varchar(255) DEFAULT NULL COMMENT 'Город клиента',
  email varchar(100) DEFAULT NULL COMMENT 'почта',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 409,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Покупатель',
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE customer
ADD CONSTRAINT FK_customer_id_type FOREIGN KEY (id_type)
REFERENCES type_position (id);

--
-- Create table `salesmans`
--
CREATE TABLE salesmans (
  id bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Код продавца',
  name varchar(50) DEFAULT NULL COMMENT 'ФИО',
  sex varchar(255) DEFAULT NULL COMMENT 'Пол продавца',
  phone varchar(255) DEFAULT NULL COMMENT 'Номер продавца',
  email varchar(100) DEFAULT NULL COMMENT 'Почта',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1638,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Владелец имущества',
ROW_FORMAT = DYNAMIC;

--
-- Create table `possessions`
--
CREATE TABLE possessions (
  id bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  adress varchar(255) DEFAULT NULL,
  city varchar(255) DEFAULT NULL COMMENT 'Город в котором недвижимость',
  square float UNSIGNED DEFAULT NULL COMMENT 'Площадь',
  id_type bigint UNSIGNED NOT NULL COMMENT 'Тип недвижимости',
  cost int UNSIGNED DEFAULT NULL COMMENT 'стоимость имущества',
  id_rieltor bigint UNSIGNED DEFAULT NULL COMMENT 'Код релтора',
  state varchar(255) DEFAULT NULL COMMENT 'Состояние объекта',
  id_salesmans bigint UNSIGNED NOT NULL COMMENT 'Код владельца',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Недвижимость',
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE possessions
ADD CONSTRAINT FK_possessions_id_rieltor FOREIGN KEY (id_rieltor)
REFERENCES rieltor (id);

--
-- Create foreign key
--
ALTER TABLE possessions
ADD CONSTRAINT FK_possessions_id_salesmans FOREIGN KEY (id_salesmans)
REFERENCES salesmans (id);

--
-- Create foreign key
--
ALTER TABLE possessions
ADD CONSTRAINT FK_possessions_id_type FOREIGN KEY (id_type)
REFERENCES type_position (id);

--
-- Create table `vision`
--
CREATE TABLE vision (
  id bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  date varchar(255) DEFAULT NULL COMMENT 'Дата просмотра',
  tyme varchar(255) DEFAULT NULL COMMENT 'Время просмотра',
  id_possetions bigint UNSIGNED NOT NULL COMMENT 'Что показывали',
  id_customer bigint UNSIGNED NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Просмотры объектов',
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE vision
ADD CONSTRAINT FK_vision_id_customer FOREIGN KEY (id_customer)
REFERENCES customer (id);

--
-- Create foreign key
--
ALTER TABLE vision
ADD CONSTRAINT FK_vision_id_possetions FOREIGN KEY (id_possetions)
REFERENCES possessions (id);

--
-- Create table `order`
--
CREATE TABLE `order` (
  id bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  date date DEFAULT NULL COMMENT 'Дата сделки',
  time time DEFAULT NULL COMMENT 'Время сделки',
  id_position bigint UNSIGNED NOT NULL COMMENT 'Код имущества',
  is_successful tinyint(1) DEFAULT NULL COMMENT 'Сделка успешная?',
  direction varchar(255) DEFAULT NULL COMMENT 'Тип совершаемой сделки',
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Сделка',
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE `order`
ADD CONSTRAINT FK_order_id_position FOREIGN KEY (id_position)
REFERENCES possessions (id);

-- 
-- Dumping data for table department
--
INSERT INTO `position`.`type_position` (`name`, `describe`)
VALUES
  ('Квартира', 'Жилая квартира в многоквартирном доме'),
  ('Дом', 'Индивидуальный жилой дом'),
  ('Таунхаус', 'Жилой дом блочной застройки с отдельным входом'),
  ('Коммерческая недвижимость', 'Офисы, магазины, торговые площади'),
  ('Земельный участок', 'Земля под жилую или коммерческую застройку'),
  ('Склад', 'Складские помещения различного назначения'),
  ('Гараж', 'Отдельно стоящий или встроенный гараж'),
  ('Апартаменты', 'Жилая недвижимость без статуса квартиры'),
  ('Новостройка', 'Недвижимость в строящемся или новом доме'),
  ('Вторичное жильё', 'Жилая недвижимость на вторичном рынке');


-- Покупатель
INSERT INTO `position`.`customer` (`name`, `phone`, `id_type`, `sex`, `city`, `email`)
VALUES
  ('Иванов С.П.', '+7-901-0000001', 1, 'Мужской', 'Москва', 'ivanov.sp@mail.ru'),
  ('Петрова А.В.', '+7-901-0000002', 2, 'Женский', 'Санкт-Петербург', 'petrova.av@mail.ru'),
  ('Сидоров А.Н.', '+7-901-0000003', 1, 'Мужской', 'Новосибирск', 'sidorov.an@mail.ru'),
  ('Кузнецова О.С.', '+7-901-0000004', 3, 'Женский', 'Екатеринбург', 'kuznetsova.os@mail.ru'),
  ('Смирнов Д.А.', '+7-901-0000005', 4, 'Мужской', 'Казань', 'smirnov.da@mail.ru'),
  ('Морозова И.П.', '+7-901-0000006', 1, 'Женский', 'Нижний Новгород', 'morozova.ip@mail.ru'),
  ('Васильев М.О.', '+7-901-0000007', 2, 'Мужской', 'Самара', 'vasiliev.mo@mail.ru'),
  ('Фёдорова Е.В.', '+7-901-0000008', 5, 'Женский', 'Омск', 'fedorova.ev@mail.ru'),
  ('Попов А.С.', '+7-901-0000009', 6, 'Мужской', 'Челябинск', 'popov.as@mail.ru'),
  ('Соколова М.А.', '+7-901-0000010', 1, 'Женский', 'Ростов-на-Дону', 'sokolova.ma@mail.ru'),
  
  ('Никитин П.И.', '+7-901-0000011', 7, 'Мужской', 'Уфа', 'nikitin.pi@mail.ru'),
  ('Орлова Н.Д.', '+7-901-0000012', 1, 'Женский', 'Красноярск', 'orlova.nd@mail.ru'),
  ('Зайцев Р.Е.', '+7-901-0000013', 2, 'Мужской', 'Пермь', 'zaitsev.re@mail.ru'),
  ('Григорьева Т.О.', '+7-901-0000014', 8, 'Женский', 'Воронеж', 'grigorieva.to@mail.ru'),
  ('Беляев А.С.', '+7-901-0000015', 4, 'Мужской', 'Волгоград', 'belyaev.as@mail.ru'),
  ('Калинина С.М.', '+7-901-0000016', 1, 'Женский', 'Краснодар', 'kalinina.sm@mail.ru'),
  ('Макаров Д.В.', '+7-901-0000017', 9, 'Мужской', 'Тюмень', 'makarov.dv@mail.ru'),
  ('Егорова А.Р.', '+7-901-0000018', 10, 'Женский', 'Ижевск', 'egorova.ar@mail.ru'),
  ('Данилов К.М.', '+7-901-0000019', 3, 'Мужской', 'Ярославль', 'danilov.km@mail.ru'),
  ('Жукова В.А.', '+7-901-0000020', 1, 'Женский', 'Тула', 'zhukova.va@mail.ru');


-- Владелец имущества
INSERT INTO `position`.`salesmans` (`name`, `sex`, `phone`, `email`)
VALUES
    ('Иванов И.И.', 'Мужской', '+49-151-1234567', 'ivanov@agency.de'),
    ('Петров П.С.', 'Мужской', '+49-151-2345678', 'petrov@agency.de'),
    ('Сидорова А.В.', 'Женский', '+49-151-3456789', 'sidorova@agency.de'),
    ('Кузнецов А.А.', 'Мужской', '+49-151-4567890', 'kuznetsov@agency.de'),
    ('Смирнова Е.О.', 'Женский', '+49-151-5678901', 'smirnova@agency.de'),
    ('Васильев Д.Н.', 'Мужской', '+49-151-6789012', 'vasiliev@agency.de'),
    ('Орлова М.И.', 'Женский', '+49-151-7890123', 'orlova@agency.de'),
    ('Фёдоров С.П.', 'Мужской', '+49-151-8901234', 'fedorov@agency.de'),
    ('Морозова Н.Е.', 'Женский', '+49-151-9012345', 'morozova@agency.de'),
    ('Зайцев А.М.', 'Мужской', '+49-151-0123456', 'zaitsev@agency.de');


-- Релторские филиалы
INSERT INTO `position`.`department` (`name`, `describe`, `city`)
VALUES
    ('Отдел по Москве', 'Покупка, продажа и аренда недвижимости', 'Москва'),
    ('Отдел по Санкт-Петербургу', 'Работа с новостройками и вторичным жильём', 'Санкт-Петербург'),
    ('Отдел по Екатеринбургу', 'Сопровождение сделок с жилой недвижимостью', 'Екатеринбург'),
    ('Отдел по Новосибирску', 'Продажа и аренда квартир и домов', 'Новосибирск'),
    ('Отдел по Подмосковью', 'Коммерческая и жилая недвижимость', 'Москва'),
    ('Отдел по Казани', 'Вторичное жильё и земельные участки', 'Казань'),
    ('Отдел по Сочи', 'Элитная недвижимость и индивидуальный подход', 'Сочи'),
    ('Отдел по Краснодару', 'Новостройки, ипотека и юридическая поддержка', 'Краснодар'),
    ('Отдел по Самаре', 'Оценка, продажа и аренда недвижимости', 'Самара'),
    ('Отдел по Нижнему Новгороду', 'Сеть риелторских агентств', 'Нижний Новгород');


-- Риэлтор
INSERT INTO `position`.`rieltor` (`name`, `id_company`, `salary`, `sex`, `birthday`)
VALUES
    ('Иванов А.С.', 1, 90000, 'Мужской', '1988-03-15'),
    ('Петрова М.В.', 1, 85000, 'Женский', '1991-07-22'),
    ('Сидоров Д.А.', 2, 80000, 'Мужской', '1985-11-02'),
    ('Кузнецова О.Н', 2, 82000, 'Женский', '1993-04-18'),
    ('Смирнов П.И.', 3, 78000, 'Мужской', '1990-09-09'),
    ('Морозова А.С.', 3, 80000, 'Женский', '1994-01-27'),
    ('Васильев М.О.', 4, 75000, 'Мужской', '1987-06-05'),
    ('Фёдорова Е.А.', 4, 77000, 'Женский', '1992-12-14'),
    ('Попов Р.Е.', 5, 95000, 'Мужской', '1984-08-30'),
    ('Соколова Ю.П.', 5, 92000, 'Женский', '1989-02-11'),

    ('Никитин А.М.', 6, 70000, 'Мужской', '1995-05-19'),
    ('Орлова Н.И.', 6, 72000, 'Женский', '1996-10-08'),
    ('Зайцев К.А.', 7, 88000, 'Мужской', '1986-03-03'),
    ('Григорьева С.О.', 7, 86000, 'Женский', '1991-07-17'),
    ('Беляев Д.С.', 8, 83000, 'Мужской', '1988-11-25'),
    ('Калинина И.М.', 8, 84000, 'Женский', '1990-01-09'),
    ('Макаров В.Р.', 9, 90000, 'Мужской', '1983-04-01'),
    ('Егорова А.Д.', 9, 89000, 'Женский', '1994-09-21'),
    ('Данилов М.Н.', 10, 87000, 'Мужской', '1987-12-06'),
    ('Жукова В.С.', 10, 88000, 'Женский', '1992-06-28');


-- Недвижимость
INSERT INTO `position`.`possessions` (`adress`, `city`, `square`, `id_type`, `cost`, `id_rieltor`, `state`, `id_salesmans`)
VALUES
    ('ул. Ленина, д. 10, кв. 45', 'Москва', 54.3, 1, 14500000, 1, 'Выставлен на продажу', 1),
    ('пр-т Мира, д. 120', 'Москва', 78.0, 2, 22500000, 2, 'Продан', 2),
    ('ул. Тверская, д. 7', 'Москва', 35.5, 1, 12800000, 3, 'Снят с продажи', 3),
    ('ул. Бауманская, д. 15', 'Москва', 92.0, 4, 31000000, 4, 'Выставлен на продажу', 4),
    ('ул. Профсоюзная, д. 88', 'Москва', 61.7, 1, 16700000, 5, 'Продан', 5),

    ('Невский пр-т, д. 55', 'Санкт-Петербург', 48.2, 1, 11900000, 6, 'Выставлен на продажу', 6),
    ('ул. Лиговский пр-т, д. 210', 'Санкт-Петербург', 70.0, 2, 18500000, 7, 'Снят с продажи', 7),
    ('ул. Рубинштейна, д. 3', 'Санкт-Петербург', 42.8, 1, 13200000, 8, 'Продан', 8),
    ('пр-т Ветеранов, д. 90', 'Санкт-Петербург', 63.0, 1, 9800000, 9, 'Выставлен на продажу', 9),
    ('ул. Савушкина, д. 118', 'Санкт-Петербург', 110.5, 4, 27000000, 10, 'Продан', 10),

    ('ул. Малышева, д. 25', 'Екатеринбург', 56.0, 1, 7800000, 11, 'Выставлен на продажу', 1),
    ('ул. Белинского, д. 100', 'Екатеринбург', 85.0, 2, 10200000, 12, 'Снят с продажи', 2),
    ('ул. Щорса, д. 60', 'Екатеринбург', 44.0, 1, 6400000, 13, 'Продан', 3),
    ('ул. Восточная, д. 15', 'Екатеринбург', 120.0, 4, 14500000, 14, 'Выставлен на продажу', 4),
    ('ул. Уральская, д. 8', 'Екатеринбург', 38.5, 1, 5700000, 15, 'Снят с продажи', 5),

    ('ул. Красный проспект, д. 70', 'Новосибирск', 52.0, 1, 6900000, 16, 'Продан', 6),
    ('ул. Фрунзе, д. 5', 'Новосибирск', 90.0, 2, 9800000, 17, 'Выставлен на продажу', 7),
    ('ул. Гоголя, д. 20', 'Новосибирск', 46.0, 1, 6200000, 18, 'Снят с продажи', 8),
    ('ул. Кирова, д. 110', 'Новосибирск', 105.0, 4, 13200000, 19, 'Выставлен на продажу', 9),
    ('ул. Дуси Ковальчук, д. 250', 'Новосибирск', 60.0, 1, 7100000, 20, 'Продан', 10),

    ('ул. Баумана, д. 12', 'Казань', 49.0, 1, 8300000, 1, 'Выставлен на продажу', 1),
    ('пр-т Победы, д. 78', 'Казань', 72.0, 2, 11500000, 2, 'Продан', 2),
    ('ул. Чистопольская, д. 40', 'Казань', 65.0, 1, 9200000, 3, 'Снят с продажи', 3),
    ('ул. Ямашева, д. 95', 'Казань', 88.0, 3, 12500000, 4, 'Выставлен на продажу', 4),
    ('ул. Адоратского, д. 3', 'Казань', 41.0, 1, 6900000, 5, 'Продан', 5),

    ('ул. Красная, д. 150', 'Краснодар', 58.0, 1, 7600000, 6, 'Выставлен на продажу', 6),
    ('ул. Северная, д. 320', 'Краснодар', 95.0, 2, 12800000, 7, 'Снят с продажи', 7),
    ('ул. Тургенева, д. 180', 'Краснодар', 47.5, 1, 6800000, 8, 'Продан', 8),
    ('ул. Селезнёва, д. 60', 'Краснодар', 110.0, 4, 15200000, 9, 'Выставлен на продажу', 9),
    ('ул. Московская, д. 140', 'Краснодар', 62.0, 1, 8200000, 10, 'Продан', 10),

    ('ул. Октябрьская, д. 20', 'Ростов-на-Дону', 55.0, 1, 7400000, 11, 'Снят с продажи', 1),
    ('ул. Большая Садовая, д. 15', 'Ростов-на-Дону', 90.0, 2, 12000000, 12, 'Выставлен на продажу', 2),
    ('ул. Социалистическая, д. 45', 'Ростов-на-Дону', 42.0, 1, 6800000, 13, 'Продан', 3),
    ('ул. Садовая, д. 90', 'Ростов-на-Дону', 100.0, 4, 14000000, 14, 'Выставлен на продажу', 4),
    ('ул. Пушкинская, д. 33', 'Ростов-на-Дону', 60.0, 1, 7200000, 15, 'Снят с продажи', 5);


-- Сделка
INSERT INTO `position`.`order` (`date`, `time`, `id_position`, `is_successful`, `direction`)
VALUES
    ('2025-12-05', '10:30:00', 1, 1, 'Покупка'),
    ('2025-12-06', '11:15:00', 2, 0, 'Продажа'),
    ('2025-12-07', '09:45:00', 3, 1, 'Покупка'),
    ('2025-12-08', '14:20:00', 4, 1, 'Продажа'),
    ('2025-12-09', '16:05:00', 5, 0, 'Покупка'),
    ('2025-12-10', '12:50:00', 6, 1, 'Продажа'),
    ('2025-12-11', '13:30:00', 7, 1, 'Покупка'),
    ('2025-12-12', '15:10:00', 8, 0, 'Продажа'),
    ('2025-12-13', '09:00:00', 9, 1, 'Покупка'),
    ('2025-12-14', '10:40:00', 10, 1, 'Продажа'),

    ('2025-12-15', '11:20:00', 11, 0, 'Покупка'),
    ('2025-12-16', '12:00:00', 12, 1, 'Продажа'),
    ('2025-12-17', '13:45:00', 13, 1, 'Покупка'),
    ('2025-12-18', '14:30:00', 14, 0, 'Продажа'),
    ('2025-12-19', '15:15:00', 15, 1, 'Покупка'),
    ('2025-12-20', '09:50:00', 16, 1, 'Продажа'),
    ('2025-12-21', '10:35:00', 17, 0, 'Покупка'),
    ('2025-12-22', '11:25:00', 18, 1, 'Продажа'),
    ('2025-12-23', '12:10:00', 19, 1, 'Покупка'),
    ('2025-12-24', '13:55:00', 20, 0, 'Продажа');


-- Просмотры объектов
INSERT INTO `position`.`vision` (`date`, `tyme`, `id_possetions`, `id_customer`)
VALUES
    ('2025-02-01', '10:00', 1, 1),
    ('2025-02-01', '11:30', 2, 1),
    ('2025-02-02', '12:00', 3, 1),
    ('2025-02-02', '14:00', 4, 1),
    ('2025-02-03', '09:30', 5, 5),
    ('2025-02-03', '10:45', 6, 6),
    ('2025-02-04', '11:15', 7, 2),
    ('2025-02-04', '13:00', 8, 2),
    ('2025-02-05', '14:30', 9, 2),
    ('2025-02-05', '15:00', 10, 2),

    ('2025-02-06', '10:20', 11, 11),
    ('2025-02-06', '11:40', 12, 12),
    ('2025-02-07', '12:10', 13, 3),
    ('2025-02-07', '13:50', 14, 3),
    ('2025-02-08', '09:45', 15, 3),
    ('2025-02-08', '10:30', 16, 3),
    ('2025-02-09', '11:05', 17, 3),
    ('2025-02-09', '12:55', 18, 18),
    ('2025-02-10', '14:15', 19, 19),
    ('2025-02-10', '15:20', 20, 20);

--
-- Restore previous SQL mode
--
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;